### ISSUE TITLE
Bug: forcing clean process.exit() on uncaughtException and hiding the thrown error

### ISSUE THREAD

**Issue by Julusian** [nytamin/threadedClass#45]
The exit handler change has introduced some breaking behaviour https://github.com/nytamin/threadedClass/commit/65000ca52010f695beeb7905c9c9774cf203be2e#diff-74357ad743c3016a7531c87588a8c0aa8a0617a4580d654eb798b94c1e01adf5R503

In companion, I found that it was 'cleanly' exiting when the spotify client library threw an exception, with no error being logged. It took some guesswork and trial and error to figure out where it was because of this.
After some digging and searching for code snippets in node_modules, I determined it was due to the uncaughtException handler registered here.
Companion doesn't register an uncaughtException handler currently, and doesnt want the process to exit if an error is thrown. But this library is forcing that to happen.
It looks like setting the undocumented `ThreadedClassManager.dontHandleExit` property will stop this happening, but does that mean I should register/manage similar logic on process exit?

I can't remember the motivation for the exit handler changes, so I don't know how we should progress on this. At the very least it should be a non-zero exit code (as that indicates a successful/normal termination).

**Comment by nytamin** [comment]
Note: after some discussion between me and @Julusian we've decided that the `dontHandleExit` functionality should be an opt-in, rather than an opt-opt.
Perhaps also make a check that the a library consume has set up an exceptionHandler, and log a warning if not.

**Comment by Julusian** [comment]
My thinking was to make dontHandleExit be `true | false | 'auto'` (probably undefined not 'auto')
Default of auto.
When true or false, it would behave as today.
If auto, then we would check if are already handlers registered.
If not, then log a warning and dont register any.
If there are, then add ours.

I'm not quite sure how it should behave if some handlers are registered and not others (eg, exit is but unhandledException isnt)
